### ISSUE TITLE
Lovely work ... broken license

### ISSUE THREAD

**Issue by tdunning** [hcfman/sbts-aru#3]
You have done some really nice work here, but ...

When you put additional constraints on the use of your software, the software is no longer subject to the Apache license. There is no problem in doing so since the software you have assembled and/or written is up to you to license however you like.

The problem comes because Github only looks at your LICENSE file when classifying your license. Since the contents of that file are exactly the Apache license, your additional constraints get ignored.

To fix this problem, you need to either

a) remove the constraints and follow the Apache license (doesn't sound like what you want)

or

b) fix the LICENSE file to say what you mean. This will result in Github marking your license as "unrecognized", but that's actually correct.

If you would like, I can produce a pull request.

**Comment by hcfman** [comment]
Sure. That’s fine. Do it.- CheersKimOn 22 Feb 2024, at 19:30, Ted Dunning ***@***.***> wrote:﻿
You have done some really nice work here, but ...
When you put additional constraints on the use of your software, the software is no longer subject to the Apache license. There is no problem in doing so since the software you have assembled and/or written is up to you to license however you like.
The problem comes because Github only looks at your LICENSE file when classifying your license. Since the contents of that file are exactly the Apache license, your additional constraints get ignored.
To fix this problem, you need to either
a) remove the constraints and follow the Apache license (doesn't sound like what you want)
or
b) fix the LICENSE file to say what you mean. This will result in Github marking your license as "unrecognized", but that's actually correct.
If you would like, I can produce a pull request.

**Comment by hcfman** [comment]
I want to be unrecognised then. So just can’t let the govt use the software for anything.- CheersKimOn 22 Feb 2024, at 19:30, Ted Dunning ***@***.***> wrote:﻿
You have done some really nice work here, but ...
When you put additional constraints on the use of your software, the software is no longer subject to the Apache license. There is no problem in doing so since the software you have assembled and/or written is up to you to license however you like.
The problem comes because Github only looks at your LICENSE file when classifying your license. Since the contents of that file are exactly the Apache license, your additional constraints get ignored.
To fix this problem, you need to either
a) remove the constraints and follow the Apache license (doesn't sound like what you want)
or
b) fix the LICENSE file to say what you mean. This will result in Github marking your license as "unrecognized", but that's actually correct.
If you would like, I can produce a pull request.

**Comment by tdunning** [comment]
Pull coming shortly.

**Comment by tdunning** [comment]
OK. I created the pull request but I note that these changes didn't change the license on my fork.

Not sure if it will work for you either. Or it may just take time to take effect.

In any case humans should have an easier read of it.

**Comment by tdunning** [comment]
For your own thoughts, is the CRA still a problem for systems like this? We were able to get a lot of improvement into the language in the end, don't you think?

**Comment by hcfman** [comment]
I'll come back to you privately on that. I'

**Comment by hcfman** [comment]
Also, I've never merged a pull request before. I thought I did the right steps, but it may have closed it without merge it. I'll look further and attempt to fix this.

**Comment by hcfman** [comment]
Yay! Pull request is merged.

**Comment by hcfman** [comment]
I'll take care of adding this version of the license to any other projects I've added it to.

**Comment by tdunning** [comment]
I confirm that Github saw the change and understands that this isn't vanilla Apache license.

Cool!
