### ISSUE TITLE
Problem with gps_event_time.py

### ISSUE THREAD

**Issue by simonik** [hcfman/sbts-aru#5]
I try to get time from our flac file, but I get :

gps_event_time.sh 2024-03-16_14-29-50.693958--sova--2024-03-16_14-29-50.693958.tracking 283.6789
Traceback (most recent call last):
  File "/home/pi/python/gps_event_time.py", line 72, in <module>
    main()
  File "/home/pi/python/gps_event_time.py", line 70, in main
    add_seconds_to_filename(args.filename, args.seconds, args.buffer_size, args.show_time_only)
  File "/home/pi/python/gps_event_time.py", line 27, in add_seconds_to_filename
    sample_rate = read_sample_rate(flac_filename)
  File "/home/pi/python/gps_event_time.py", line 12, in read_sample_rate
    return int(info['sample_rate'])
KeyError: 'sample_rate'
pi@sova:~/sbts-aru$ gps_event_time.sh 2024-03-16_14-29-50.693958--sova--2024-03-16_14-29-50.693958.tracking 28.0
Traceback (most recent call last):
  File "/home/pi/python/gps_event_time.py", line 72, in <module>
    main()
  File "/home/pi/python/gps_event_time.py", line 70, in main
    add_seconds_to_filename(args.filename, args.seconds, args.buffer_size, args.show_time_only)
  File "/home/pi/python/gps_event_time.py", line 27, in add_seconds_to_filename
    sample_rate = read_sample_rate(flac_filename)
  File "/home/pi/python/gps_event_time.py", line 12, in read_sample_rate
    return int(info['sample_rate'])
KeyError: 'sample_rate'

What is wrong?  Value 283.6789 is only for test.

Thanks

**Comment by hcfman** [comment]
I think you should be running it with the wrapper program that is in ~/sbts-bin called gps_event_time.sh

so something like:

~/sbts-bin/gps_event_time.sh 2024-03-16_14-29-50.693958--sova--2024-03-16_14-29-50.693958.tracking 283.6789

Originally I was using just the python code, but when it came to using opensoundscape I found it prudent to use a wrapper script and virtualenvs.

It looks like you have a problem accessing

from pydub.utils import mediainfo

And that is because that's in the virtualenv that the wrapper script sets up.

I'll check all of my documentation and fix any references where I have been using the python script without the wrapper, thanks for that.

**Comment by hcfman** [comment]
I see that in my medium.com article I mentioned gps_event_time.sh but then in the example I use the .py version. The example on github is correctly specified using the .sh wrapper version that sets up the libraries correctly using the virtualenv

**Comment by simonik** [comment]
Thanks,
I ran script gps_event_time.sh but from directory sbts-aru.
Now I run script from sbts-bin: 
root@sova:/home/pi/sbts-bin# ./gps_event_time.sh 2024-03-16_14-29-50.693958--sova--2024-03-16_14-29-50.693958.tracking 283.6789

Traceback (most recent call last):
  File "/home/pi/python/gps_event_time.py", line 72, in <module>
    main()
  File "/home/pi/python/gps_event_time.py", line 70, in main
    add_seconds_to_filename(args.filename, args.seconds, args.buffer_size, args.show_time_only)
  File "/home/pi/python/gps_event_time.py", line 27, in add_seconds_to_filename
    sample_rate = read_sample_rate(flac_filename)
  File "/home/pi/python/gps_event_time.py", line 12, in read_sample_rate
    return int(info['sample_rate'])
KeyError: 'sample_rate'

**Comment by hcfman** [comment]
Your file is not in the sbts-bin directory I think. The file:

2024-03-16_14-29-50.693958--sova--2024-03-16_14-29-50.693958.tracking

Should be in a directory  at ~/disk/audio/sova/2024/2024-03/2024-03-16 I think.

So from that directory you should run:

./gps_event_time.sh ~/disk/audio/sova/2024/2024-03/2024-03-16/2024-03-16_14-29-50.693958--sova--2024-03-16_14-29-50.693958.tracking 283.6789

I think.

Having said that, there's not proper error message that the file doesn't exist which might have made the problem more evident. That's not cool. I'll fix that.

Also, my examples in github could have been more like in real life. I guess I was distracted by the fact that I myself run this commands on another host :-(

Hope that helps.

**Comment by hcfman** [comment]
And I’d recommend running those commands as the normal pi user. Mainly because you can and because I didn’t test things running as the root user.

**Comment by hcfman** [comment]
I think that should solve your problems.

However, python sometimes writes files in the places where it's code is. If you run programs as root and it creates a file there with root permissions then you might find it doesn't run as user pi anymore.

I doubt this is your case, but start runing as the normal user and check with something like:

find virtualenvs -user root

And change it back to user pi with chown pi:pi file if you find one.

**Comment by simonik** [comment]
Hello,
thank you very much. The problem was that I wasn't in the directory with the recording. Now it seems to be working.

pi@sova:~/disk/sova/2024/2024-03/2024-03-18$ /home/pi/sbts-bin/gps_event_time.sh 2024-03-18_09-46-07.681632--sova--2024-03-18_09-56-07.636080.tracking 280.365

Result:
2024-03-18_09-50-47.995628

I have yet to buy a new NEO 7M because I have a fake one.
The module takes even 1 hour to fix.

**Comment by hcfman** [comment]
Yeah, I'm usually on a different computer altogether and I've copied the files there. Because I would need recordings from at least three recorders to start localizing. Also because you would need a Raspberry Pi 4 or higher to localize on the Pi itself. Smaller doesn't have enough memory to install the localization libraries.

Feel free to stay in touch in you wish, you can contact me through linkedin.

https://www.linkedin.com/in/kim-hendrikse-2427643/

Of course fine if not as well.

I didn't even know they had fakes. Make's me wonder what I have. They only cost 7 euros. But they sync up fine. Some neo 8's I had were bad at synching. Maybe these were fakes.
