### ISSUE TITLE
Use edge impulse library 

### ISSUE THREAD

**Issue by Boukenjo** [hcfman/sbts-aru#6]
Hello Mr. Hendrikse !

We are a group of engineering students working on monitoring an endangered bird species (the capercaillie), and we planned to use TDOA to localise the bird, so your project seems that it could help us a lot ! 
We are curious if it was possible to adapt your project by using a custom library we made on edge impulse with recordings of the sound of the bird we are monitoring ? And even add a Lora device to your device to make remote communication in places where there is no internet connection ? 
Also about the project it self, we don't understand how the 4 devices are communicating between them. Is the localisation done in real time (or remotely), or is it calculated after collecting all the devices after a time of recording ? 
About the hardware and just to be sure, we have to buy four times all the pieces you give in the hardware requirements (4 rasberry pi etc) ? 
Last but no least, do you think it would be possible for us to make your project work in one month of time or are we gonna face too many issues in the implementation ?
Please find these numerous questions as the expression of our deep interest for your work. We are grateful for any information you would share.

Best regards,
Five Swiss EPFL students

**Comment by hcfman** [comment]
Sounds very interesting! Yes, you would need 4x copies of the equipment. Because unlike sound localization by phase difference of arrival TDOA based sound localization is typically over larger distances and needs 4x independent microphones to record the sounds and have precise clocks, which this project takes care of.

Lora is a good suggestion if you have no other equipment around. One system would need to do the localization but it would need to precise start times of the sounds from it's other collaborators. This start time could be transmitted by lora. Point to point lora and not lorawan as you indicated not having a network connection.

Making it work in a month's time would depend on your capabilities. Most importantly is what you have outside of my project. Do you already have a pipeline capable of determining the start time to a high precision? i.e. 1ms or at most a few milliseconds I think. If you have that and you are expert and hooking up point to point lora you might have a chance. But realistically I think it's going to take a bunch longer. Each device would have to determine the start time, then transmitt this info to a single host, then this host would have to calculate the TDOA. Then the result transmitted by lora again. Note, you will likely need a mechanism to avoid Lora collisions as well. You would need to consume the jackd sound stream, look at the current code to see how that works. And look at the current code how it feeds the tracking file, because that's how you will need to get the time exactly.

Feel free to send me a linkedin invitation and we can discuss it over a google meet meeting if you like:

https://www.linkedin.com/in/kim-hendrikse-2427643/

I would be impressed as hell if you managed to make all this work within a month. You won't have trouble finding work.

**Comment by Boukenjo** [comment]
Thank you for your really fast answer !

Since we have an important deadline in a bit less than one month we are gonna keep things simple for the moment, but we will keep in mind what you said to maybe improve our device later (it looks really really interesting).  
We will still command the hardware to start getting used to your project in parallel of what we are working on.
Again a big thank you,
Have a nice day !
